version: "3.9"

services:
  healthcare_app:
    image: healthcare-app
    container_name: healthcare_container
    ports:
      - "80:9000"
    volumes:
      - db_data:/app/data
    environment:
      - FLASK_ENV=production

volumes:
  db_data:
